services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: /main
    restart: always
    depends_on:
      - db
      - prometheus

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.prod.yml:/etc/prometheus/prometheus.prod.yml
    ports:
      - "9090:9090"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
volumes:
  app:
  db:
  redis_data:
  grafana_data:
