env: "development"

database:
  host: "localhost"
  port: "5439"
  user: "postgres"
  dbname: "test"
  max_attempts: 10

servers:
  http:
    port: "8080"
    host: "0.0.0.0"
    timeout: 5s
    idle_timeout: 60s

redis:
  host: "localhost"
  port: "6380"
  password: ""
  dbnumber: 0

prometheus:
  host: "localhost"
  port: 8081
  timeout: 4s
  debug: true
  idle_timeout: 60s
