global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "users-info"

    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ["host.docker.internal:8081"]
